site_name: SendCloud 文档中心

site_url: http://sendcloud.sohu.com

#repo_url: https://github.com/liubida/sendcloud_docs.git
repo_url: https://github.com/sendcloud2013/sendcloud_docs/blob/master/sources/index.md

docs_dir: sources

#theme_dir: theme/updocs

theme_center_lead: false

include_search: true

copyright: Copyright &copy; 2015, SendCloud

author: liubida && lianzimi

pages:
# Develop Guide
# - ['guide/index.md', '开发指南', '开发者指南']
# - ['guide/php_rest_guide.md', '开发指南', 'REST API 简易指南（PHP）']
#
- [index.md]
- [guide/base.md, '开发者指南', '基本概念']
- [guide/advance.md, '开发者指南', '高级功能']

- [email/index.md, '邮件API', '规则']
- [email/send_email.md, '邮件API', '邮件发送']
#- [email/send_email_smtp.md, '邮件API', '邮件发送SMTPAPI']
- [email/template_do.md, '邮件API', '邮件模板']
- [email/list_do.md, '邮件API', '地址列表']
- [email/label_do.md, '邮件API', '邮件标签']
- [email/queuestatus_do.md, '邮件API', '队列状态']
- [email/stats_do.md, '邮件API', '数据统计']
- [email/user_info.md, '邮件API', '用户信息']
- [email/bounce_do.md, '邮件API', '退信列表管理']
- [email/unsubscribe_do.md, '邮件API', '取消订阅管理']
- [email/spamreported_do.md, '邮件API', '垃圾举报管理']
- [email/webhook.md, '邮件API', 'webhook参数说明']

- [sms/index.md, '短信API', '短信API']

- [downloads/index.md, '资源下载', '资源下载']
- [downloads/code/curl.md, '资源下载','Curl']
- [downloads/code/python.md, '资源下载','Python']
- [downloads/code/java.md, '资源下载','Java']
- [downloads/code/php.md, '资源下载','Php']
- [downloads/code/ruby.md, '资源下载','Ruby']
- [downloads/code/perl.md, '资源下载','Perl']
- [downloads/code/csharp.md, '资源下载','C#']

- [faq/index.md, 'FAQ', 'FAQ']

#theme: readthedocs


