site_name: SendCloud 文档中心

site_url: http://docs.upyun.com/

repo_url: https://github.com/upyun/docs/

docs_dir: sources

#theme_dir: theme/updocs

theme_center_lead: false

include_search: true

copyright: Copyright &copy; 2015, SendCloud

pages:
- [index.md]
- [guide.md, '引言']
- [email.md, '邮件API']
- [sms.md, '短信API']

theme: readthedocs


