site_name: SendCloud 文档中心

site_url: http://docs.upyun.com/

repo_url: https://github.com/upyun/docs/

docs_dir: sources

#theme_dir: theme/updocs

theme_center_lead: false

include_search: true

copyright: Copyright &copy; 2015, SendCloud

author: liubida && lianzimi

pages:
# Develop Guide
# - ['guide/index.md', '开发指南', '开发者指南']
# - ['guide/php_rest_guide.md', '开发指南', 'REST API 简易指南（PHP）']
#
- [index.md]
- [guide/base.md, '开发者指南', '基本概念']
- [guide/advance.md, '开发者指南', '高级功能']

- [email/index.md, '邮件API', '传送门']
- [email/send_email.md, '邮件API', '邮件发送API']
- [email/template_do.md, '邮件API', '模板管理API']
- [email/queuestatus_do.md, '邮件API', '队列状态管理API']
- [email/invalidstat_do.md, '邮件API', '无效子类统计API']
- [email/stathour_do.md, '邮件API', '按小时邮件发送数据统计API']
- [email/stats_do.md, '邮件API', '数据统计API']
- [email/spamreported_do.md, '邮件API', '垃圾举报查询API']
- [email/unsubscribe_do.md, '邮件API', '取消订阅管理API']

- [sms/index.md, '短信API', '短信API']

- [downloads/index.md, '资源下载', '资源下载']

- [faq/index.md, 'FAQ', 'FAQ']

#theme: readthedocs


